package vm

import (
	"bufio"
	"encoding/hex"
	"os"
	"strings"
	"testing"

	tcommon "github.com/tronprotocol/go-tron/common"
)

// TestJavaHashMapOrderMatchesGolden is the SV-2 golden-alignment gate. It replays
// 324 cases generated by testdata/java_hashmap_order/GenHashMapOrder.java with the
// REAL com.google.protobuf.ByteString (protobuf-java 3.25.8, the version java-tron
// pins) inside a real java.util.HashMap, and asserts javaHashMapOrder reproduces
// the entrySet() iteration order byte-for-byte. That order is the order
// VoteWitnessProcessor.execute appends votes to the account's `votes` field
// (VoteWitnessProcessor.java:105-108), so it is consensus-load-bearing.
//
// Coverage: sizes 1..30 (random, 6 trials each); adversarial same-bucket
// collisions across buckets {0,1,cap-1,cap/2} for the real table size; and
// resize-boundary stress at k=11/12/13/23/24/25/30 with addresses straddling the
// high bit that decides the lo/hi split on each table grow. 285/324 cases have
// out != in (real reordering), so an identity/insertion-order implementation
// fails immediately.
func TestJavaHashMapOrderMatchesGolden(t *testing.T) {
	f, err := os.Open("testdata/java_hashmap_order/golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer f.Close()

	parseAddrs := func(field string) []tcommon.Address {
		field = strings.TrimSpace(field)
		if field == "" {
			return nil
		}
		parts := strings.Split(field, ",")
		out := make([]tcommon.Address, 0, len(parts))
		for _, p := range parts {
			raw, err := hex.DecodeString(strings.TrimSpace(p))
			if err != nil {
				t.Fatalf("bad hex %q: %v", p, err)
			}
			if len(raw) != 21 {
				t.Fatalf("address %q not 21 bytes (got %d)", p, len(raw))
			}
			var a tcommon.Address
			copy(a[:], raw)
			out = append(out, a)
		}
		return out
	}

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	cases, reordered := 0, 0
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Split(line, ";")
		if len(fields) != 3 {
			t.Fatalf("malformed golden line: %q", line)
		}
		in := parseAddrs(fields[1])
		want := parseAddrs(fields[2])
		if len(in) != len(want) {
			t.Fatalf("case size mismatch in=%d want=%d: %q", len(in), len(want), line)
		}
		got := javaHashMapOrder(in)
		if len(got) != len(want) {
			t.Fatalf("javaHashMapOrder length got=%d want=%d for in=%v", len(got), len(want), in)
		}
		for i := range want {
			if got[i] != want[i] {
				t.Fatalf("order mismatch (k=%d) at index %d:\n in  =%s\n got =%s\n want=%s",
					len(in), i, addrsHex(in), addrsHex(got), addrsHex(want))
			}
		}
		cases++
		if !addrsEqual(in, want) {
			reordered++
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatalf("scan golden: %v", err)
	}
	if cases < 300 {
		t.Fatalf("expected the full golden corpus (>=300 cases), only read %d — testdata missing?", cases)
	}
	if reordered < 100 {
		t.Fatalf("golden corpus has too few reordered cases (%d) — test lacks teeth", reordered)
	}
	t.Logf("SV-2 golden: %d cases, %d with out!=in", cases, reordered)
}

func addrsEqual(a, b []tcommon.Address) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func addrsHex(a []tcommon.Address) string {
	var sb strings.Builder
	for i, x := range a {
		if i > 0 {
			sb.WriteByte(',')
		}
		sb.WriteString(hex.EncodeToString(x[:]))
	}
	return sb.String()
}
