// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: p2p/Connect.proto

package p2p

import (
	core "github.com/tronprotocol/go-tron/proto/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DisconnectReason — values from libp2p Connect.java + DisconnectCode.java
type DisconnectReason int32

const (
	DisconnectReason_PEER_QUITING                DisconnectReason = 0
	DisconnectReason_BAD_PROTOCOL                DisconnectReason = 1
	DisconnectReason_TOO_MANY_PEERS              DisconnectReason = 2
	DisconnectReason_DUPLICATE_PEER              DisconnectReason = 3
	DisconnectReason_DIFFERENT_VERSION           DisconnectReason = 4
	DisconnectReason_RANDOM_ELIMINATION          DisconnectReason = 5
	DisconnectReason_EMPTY_MESSAGE               DisconnectReason = 6
	DisconnectReason_PING_TIMEOUT                DisconnectReason = 7
	DisconnectReason_DISCOVER_MODE               DisconnectReason = 8
	DisconnectReason_NO_SUCH_MESSAGE             DisconnectReason = 10
	DisconnectReason_BAD_MESSAGE                 DisconnectReason = 11
	DisconnectReason_TOO_MANY_PEERS_WITH_SAME_IP DisconnectReason = 12
	DisconnectReason_RECENT_DISCONNECT           DisconnectReason = 13
	DisconnectReason_DUP_HANDSHAKE               DisconnectReason = 14
	DisconnectReason_UNKNOWN                     DisconnectReason = 255
)

// Enum value maps for DisconnectReason.
var (
	DisconnectReason_name = map[int32]string{
		0:   "PEER_QUITING",
		1:   "BAD_PROTOCOL",
		2:   "TOO_MANY_PEERS",
		3:   "DUPLICATE_PEER",
		4:   "DIFFERENT_VERSION",
		5:   "RANDOM_ELIMINATION",
		6:   "EMPTY_MESSAGE",
		7:   "PING_TIMEOUT",
		8:   "DISCOVER_MODE",
		10:  "NO_SUCH_MESSAGE",
		11:  "BAD_MESSAGE",
		12:  "TOO_MANY_PEERS_WITH_SAME_IP",
		13:  "RECENT_DISCONNECT",
		14:  "DUP_HANDSHAKE",
		255: "UNKNOWN",
	}
	DisconnectReason_value = map[string]int32{
		"PEER_QUITING":                0,
		"BAD_PROTOCOL":                1,
		"TOO_MANY_PEERS":              2,
		"DUPLICATE_PEER":              3,
		"DIFFERENT_VERSION":           4,
		"RANDOM_ELIMINATION":          5,
		"EMPTY_MESSAGE":               6,
		"PING_TIMEOUT":                7,
		"DISCOVER_MODE":               8,
		"NO_SUCH_MESSAGE":             10,
		"BAD_MESSAGE":                 11,
		"TOO_MANY_PEERS_WITH_SAME_IP": 12,
		"RECENT_DISCONNECT":           13,
		"DUP_HANDSHAKE":               14,
		"UNKNOWN":                     255,
	}
)

func (x DisconnectReason) Enum() *DisconnectReason {
	p := new(DisconnectReason)
	*p = x
	return p
}

func (x DisconnectReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisconnectReason) Descriptor() protoreflect.EnumDescriptor {
	return file_p2p_Connect_proto_enumTypes[0].Descriptor()
}

func (DisconnectReason) Type() protoreflect.EnumType {
	return &file_p2p_Connect_proto_enumTypes[0]
}

func (x DisconnectReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DisconnectReason.Descriptor instead.
func (DisconnectReason) EnumDescriptor() ([]byte, []int) {
	return file_p2p_Connect_proto_rawDescGZIP(), []int{0}
}

type CompressMessage_CompressType int32

const (
	CompressMessage_uncompress CompressMessage_CompressType = 0 // more compression types may exist; only 'uncompress' is confirmed from the Java class
)

// Enum value maps for CompressMessage_CompressType.
var (
	CompressMessage_CompressType_name = map[int32]string{
		0: "uncompress",
	}
	CompressMessage_CompressType_value = map[string]int32{
		"uncompress": 0,
	}
)

func (x CompressMessage_CompressType) Enum() *CompressMessage_CompressType {
	p := new(CompressMessage_CompressType)
	*p = x
	return p
}

func (x CompressMessage_CompressType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompressMessage_CompressType) Descriptor() protoreflect.EnumDescriptor {
	return file_p2p_Connect_proto_enumTypes[1].Descriptor()
}

func (CompressMessage_CompressType) Type() protoreflect.EnumType {
	return &file_p2p_Connect_proto_enumTypes[1]
}

func (x CompressMessage_CompressType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompressMessage_CompressType.Descriptor instead.
func (CompressMessage_CompressType) EnumDescriptor() ([]byte, []int) {
	return file_p2p_Connect_proto_rawDescGZIP(), []int{4, 0}
}

// HelloMessage — sent by both sides immediately after TCP connect.
type HelloMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *core.Endpoint         `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	NetworkId     int32                  `protobuf:"varint,2,opt,name=networkId,proto3" json:"networkId,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`           // Optional DisconnectCode on rejection; 0 (NORMAL) on accept
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ms since epoch
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`     // Parameter.version, currently 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloMessage) Reset() {
	*x = HelloMessage{}
	mi := &file_p2p_Connect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloMessage) ProtoMessage() {}

func (x *HelloMessage) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_Connect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloMessage.ProtoReflect.Descriptor instead.
func (*HelloMessage) Descriptor() ([]byte, []int) {
	return file_p2p_Connect_proto_rawDescGZIP(), []int{0}
}

func (x *HelloMessage) GetFrom() *core.Endpoint {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *HelloMessage) GetNetworkId() int32 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *HelloMessage) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HelloMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HelloMessage) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// StatusMessage — exchanged after handshake, reports peer capacity.
type StatusMessage struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	From               *core.Endpoint         `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Version            int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	NetworkId          int32                  `protobuf:"varint,3,opt,name=networkId,proto3" json:"networkId,omitempty"`
	MaxConnections     int32                  `protobuf:"varint,4,opt,name=maxConnections,proto3" json:"maxConnections,omitempty"`
	CurrentConnections int32                  `protobuf:"varint,5,opt,name=currentConnections,proto3" json:"currentConnections,omitempty"`
	Timestamp          int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatusMessage) Reset() {
	*x = StatusMessage{}
	mi := &file_p2p_Connect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusMessage) ProtoMessage() {}

func (x *StatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_Connect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusMessage.ProtoReflect.Descriptor instead.
func (*StatusMessage) Descriptor() ([]byte, []int) {
	return file_p2p_Connect_proto_rawDescGZIP(), []int{1}
}

func (x *StatusMessage) GetFrom() *core.Endpoint {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *StatusMessage) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StatusMessage) GetNetworkId() int32 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *StatusMessage) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *StatusMessage) GetCurrentConnections() int32 {
	if x != nil {
		return x.CurrentConnections
	}
	return 0
}

func (x *StatusMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// KeepAliveMessage — payload of KEEP_ALIVE_PING and KEEP_ALIVE_PONG.
type KeepAliveMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ms since epoch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAliveMessage) Reset() {
	*x = KeepAliveMessage{}
	mi := &file_p2p_Connect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAliveMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveMessage) ProtoMessage() {}

func (x *KeepAliveMessage) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_Connect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveMessage.ProtoReflect.Descriptor instead.
func (*KeepAliveMessage) Descriptor() ([]byte, []int) {
	return file_p2p_Connect_proto_rawDescGZIP(), []int{2}
}

func (x *KeepAliveMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// P2pDisconnectMessage — sent before closing a connection.
type P2PDisconnectMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        DisconnectReason       `protobuf:"varint,1,opt,name=reason,proto3,enum=p2p.DisconnectReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PDisconnectMessage) Reset() {
	*x = P2PDisconnectMessage{}
	mi := &file_p2p_Connect_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PDisconnectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PDisconnectMessage) ProtoMessage() {}

func (x *P2PDisconnectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_Connect_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PDisconnectMessage.ProtoReflect.Descriptor instead.
func (*P2PDisconnectMessage) Descriptor() ([]byte, []int) {
	return file_p2p_Connect_proto_rawDescGZIP(), []int{3}
}

func (x *P2PDisconnectMessage) GetReason() DisconnectReason {
	if x != nil {
		return x.Reason
	}
	return DisconnectReason_PEER_QUITING
}

// CompressMessage — wraps a compressed application-layer message.
type CompressMessage struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Type          CompressMessage_CompressType `protobuf:"varint,1,opt,name=type,proto3,enum=p2p.CompressMessage_CompressType" json:"type,omitempty"`
	Data          []byte                       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompressMessage) Reset() {
	*x = CompressMessage{}
	mi := &file_p2p_Connect_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressMessage) ProtoMessage() {}

func (x *CompressMessage) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_Connect_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressMessage.ProtoReflect.Descriptor instead.
func (*CompressMessage) Descriptor() ([]byte, []int) {
	return file_p2p_Connect_proto_rawDescGZIP(), []int{4}
}

func (x *CompressMessage) GetType() CompressMessage_CompressType {
	if x != nil {
		return x.Type
	}
	return CompressMessage_uncompress
}

func (x *CompressMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_p2p_Connect_proto protoreflect.FileDescriptor

const file_p2p_Connect_proto_rawDesc = "" +
	"\n" +
	"\x11p2p/Connect.proto\x12\x03p2p\x1a\x13core/Discover.proto\"\xa0\x01\n" +
	"\fHelloMessage\x12&\n" +
	"\x04from\x18\x01 \x01(\v2\x12.protocol.EndpointR\x04from\x12\x1c\n" +
	"\tnetworkId\x18\x02 \x01(\x05R\tnetworkId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\"\xe5\x01\n" +
	"\rStatusMessage\x12&\n" +
	"\x04from\x18\x01 \x01(\v2\x12.protocol.EndpointR\x04from\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x1c\n" +
	"\tnetworkId\x18\x03 \x01(\x05R\tnetworkId\x12&\n" +
	"\x0emaxConnections\x18\x04 \x01(\x05R\x0emaxConnections\x12.\n" +
	"\x12currentConnections\x18\x05 \x01(\x05R\x12currentConnections\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"0\n" +
	"\x10KeepAliveMessage\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"E\n" +
	"\x14P2pDisconnectMessage\x12-\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x15.p2p.DisconnectReasonR\x06reason\"|\n" +
	"\x0fCompressMessage\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.p2p.CompressMessage.CompressTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x1e\n" +
	"\fCompressType\x12\x0e\n" +
	"\n" +
	"uncompress\x10\x00*\xc4\x02\n" +
	"\x10DisconnectReason\x12\x10\n" +
	"\fPEER_QUITING\x10\x00\x12\x10\n" +
	"\fBAD_PROTOCOL\x10\x01\x12\x12\n" +
	"\x0eTOO_MANY_PEERS\x10\x02\x12\x12\n" +
	"\x0eDUPLICATE_PEER\x10\x03\x12\x15\n" +
	"\x11DIFFERENT_VERSION\x10\x04\x12\x16\n" +
	"\x12RANDOM_ELIMINATION\x10\x05\x12\x11\n" +
	"\rEMPTY_MESSAGE\x10\x06\x12\x10\n" +
	"\fPING_TIMEOUT\x10\a\x12\x11\n" +
	"\rDISCOVER_MODE\x10\b\x12\x13\n" +
	"\x0fNO_SUCH_MESSAGE\x10\n" +
	"\x12\x0f\n" +
	"\vBAD_MESSAGE\x10\v\x12\x1f\n" +
	"\x1bTOO_MANY_PEERS_WITH_SAME_IP\x10\f\x12\x15\n" +
	"\x11RECENT_DISCONNECT\x10\r\x12\x11\n" +
	"\rDUP_HANDSHAKE\x10\x0e\x12\f\n" +
	"\aUNKNOWN\x10\xff\x01BI\n" +
	"\x13org.tron.p2p.protosB\aConnectZ)github.com/tronprotocol/go-tron/proto/p2pb\x06proto3"

var (
	file_p2p_Connect_proto_rawDescOnce sync.Once
	file_p2p_Connect_proto_rawDescData []byte
)

func file_p2p_Connect_proto_rawDescGZIP() []byte {
	file_p2p_Connect_proto_rawDescOnce.Do(func() {
		file_p2p_Connect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_p2p_Connect_proto_rawDesc), len(file_p2p_Connect_proto_rawDesc)))
	})
	return file_p2p_Connect_proto_rawDescData
}

var file_p2p_Connect_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_p2p_Connect_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_p2p_Connect_proto_goTypes = []any{
	(DisconnectReason)(0),             // 0: p2p.DisconnectReason
	(CompressMessage_CompressType)(0), // 1: p2p.CompressMessage.CompressType
	(*HelloMessage)(nil),              // 2: p2p.HelloMessage
	(*StatusMessage)(nil),             // 3: p2p.StatusMessage
	(*KeepAliveMessage)(nil),          // 4: p2p.KeepAliveMessage
	(*P2PDisconnectMessage)(nil),      // 5: p2p.P2pDisconnectMessage
	(*CompressMessage)(nil),           // 6: p2p.CompressMessage
	(*core.Endpoint)(nil),             // 7: protocol.Endpoint
}
var file_p2p_Connect_proto_depIdxs = []int32{
	7, // 0: p2p.HelloMessage.from:type_name -> protocol.Endpoint
	7, // 1: p2p.StatusMessage.from:type_name -> protocol.Endpoint
	0, // 2: p2p.P2pDisconnectMessage.reason:type_name -> p2p.DisconnectReason
	1, // 3: p2p.CompressMessage.type:type_name -> p2p.CompressMessage.CompressType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_p2p_Connect_proto_init() }
func file_p2p_Connect_proto_init() {
	if File_p2p_Connect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_p2p_Connect_proto_rawDesc), len(file_p2p_Connect_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_p2p_Connect_proto_goTypes,
		DependencyIndexes: file_p2p_Connect_proto_depIdxs,
		EnumInfos:         file_p2p_Connect_proto_enumTypes,
		MessageInfos:      file_p2p_Connect_proto_msgTypes,
	}.Build()
	File_p2p_Connect_proto = out.File
	file_p2p_Connect_proto_goTypes = nil
	file_p2p_Connect_proto_depIdxs = nil
}
