package strictmath

import (
	"bufio"
	"fmt"
	"math"
	"os"
	"strconv"
	"strings"
	"testing"
)

// TestPow_BitIdenticalToJavaStrictMath replays the oracle vector under
// testdata/oracle/ (generated by testdata/gen.sh from a Java
// `StrictMath.pow` reference) and asserts every result matches
// bit-for-bit. A single failing pair means the port has drifted from
// fdlibm — fix the algorithm, do not relax the test.
func TestPow_BitIdenticalToJavaStrictMath(t *testing.T) {
	inputs, err := os.Open("testdata/oracle/inputs.txt")
	if err != nil {
		t.Fatalf("open inputs: %v", err)
	}
	defer inputs.Close()
	expected, err := os.Open("testdata/oracle/expected.txt")
	if err != nil {
		t.Fatalf("open expected: %v", err)
	}
	defer expected.Close()

	iScan := bufio.NewScanner(inputs)
	eScan := bufio.NewScanner(expected)

	var checked int
	var failures int
	for iScan.Scan() {
		line := strings.TrimSpace(iScan.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.Fields(line)
		if len(parts) != 2 {
			t.Fatalf("bad input line: %q", line)
		}
		a, err := parseDouble(parts[0])
		if err != nil {
			t.Fatalf("parse %q: %v", parts[0], err)
		}
		b, err := parseDouble(parts[1])
		if err != nil {
			t.Fatalf("parse %q: %v", parts[1], err)
		}
		if !eScan.Scan() {
			t.Fatalf("expected file ran out at input line %q", line)
		}
		wantHex := strings.TrimSpace(eScan.Text())
		wantBits, err := strconv.ParseUint(wantHex, 16, 64)
		if err != nil {
			t.Fatalf("parse expected %q: %v", wantHex, err)
		}

		got := Pow(a, b)
		gotBits := math.Float64bits(got)
		// Match Java's `Double.doubleToLongBits` semantics: the JDK
		// spec (java.lang.Double#doubleToLongBits) collapses every
		// NaN payload to the canonical 0x7ff8000000000000 bit
		// pattern. Without this normalisation Go's `math.NaN()`
		// (payload 0x...001) would diverge from Java's canonical NaN
		// even though both represent the same value — and the only
		// difference would be reporting, not actual chain semantics.
		if math.IsNaN(got) {
			gotBits = 0x7ff8000000000000
		}
		if gotBits != wantBits {
			failures++
			want := math.Float64frombits(wantBits)
			t.Errorf("Pow(%s, %s):\n  got  bits=%016x value=%g\n  want bits=%016x value=%g\n  diff = %g (%d ULP-ish)",
				formatDouble(a), formatDouble(b),
				gotBits, got,
				wantBits, want,
				got-want,
				int64(gotBits)-int64(wantBits))
		}
		checked++
	}
	if err := iScan.Err(); err != nil {
		t.Fatalf("scan inputs: %v", err)
	}
	if eScan.Scan() {
		t.Fatalf("expected file has extra line(s) past inputs: %q", eScan.Text())
	}
	if checked == 0 {
		t.Fatal("no vectors checked — testdata appears empty")
	}
	t.Logf("validated %d oracle vectors", checked)
	if failures > 0 {
		t.Logf("%d vectors disagreed with the Java oracle", failures)
	}
}

// parseDouble accepts Java's `Double.toHexString` form (`0x1.8p3`),
// plain decimal, and Java's literal "NaN" / "Infinity" / "-Infinity"
// strings.
func parseDouble(s string) (float64, error) {
	switch s {
	case "NaN":
		return math.NaN(), nil
	case "Infinity", "+Infinity":
		return math.Inf(1), nil
	case "-Infinity":
		return math.Inf(-1), nil
	}
	return strconv.ParseFloat(s, 64)
}

// formatDouble formats a float64 the same way Java's `Double.toString`
// would render it for the failure messages — but our priority is
// reproducibility, not Java-exact text. Use Go's default with the
// underlying bits annotated.
func formatDouble(d float64) string {
	return fmt.Sprintf("%g (bits=%016x)", d, math.Float64bits(d))
}
