// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: core/historystate/historystate.proto

// historystate.proto is a gtron-only addition (NOT imported from java-tron).
// It is the on-disk schema for the State History Index (SHI) feature — the
// reverse "(blockNum, key) → pre-value" log that lets archive nodes answer
// historical state queries without re-execution.
//
// See docs/superpowers/specs/2026-05-19-state-history-index-design.md for
// the design and the surrounding storage layout (sh-m-, sh-a-, sh-s-,
// sh-i-a-, sh-i-s-, sh-cfg- prefixes in core/rawdb/schema.go).

package historystate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StateHistoryMeta is the per-block manifest written under the sh-m- prefix.
// It records what the block changed so that read paths can bail out cheaply
// when a block didn't touch the queried key, and so that operators have a
// per-block summary for diagnostics and pruning.
type StateHistoryMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNum      uint64                 `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`  // 32-byte block hash for cross-checking on read
	NumAddrs      uint32                 `protobuf:"varint,3,opt,name=num_addrs,json=numAddrs,proto3" json:"num_addrs,omitempty"`    // count of sh-a- rows written for this block
	NumSlots      uint32                 `protobuf:"varint,4,opt,name=num_slots,json=numSlots,proto3" json:"num_slots,omitempty"`    // count of sh-s- rows written for this block
	SchemaVer     uint32                 `protobuf:"varint,5,opt,name=schema_ver,json=schemaVer,proto3" json:"schema_ver,omitempty"` // bump whenever the encoding/key layout changes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateHistoryMeta) Reset() {
	*x = StateHistoryMeta{}
	mi := &file_core_historystate_historystate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateHistoryMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateHistoryMeta) ProtoMessage() {}

func (x *StateHistoryMeta) ProtoReflect() protoreflect.Message {
	mi := &file_core_historystate_historystate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateHistoryMeta.ProtoReflect.Descriptor instead.
func (*StateHistoryMeta) Descriptor() ([]byte, []int) {
	return file_core_historystate_historystate_proto_rawDescGZIP(), []int{0}
}

func (x *StateHistoryMeta) GetBlockNum() uint64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *StateHistoryMeta) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *StateHistoryMeta) GetNumAddrs() uint32 {
	if x != nil {
		return x.NumAddrs
	}
	return 0
}

func (x *StateHistoryMeta) GetNumSlots() uint32 {
	if x != nil {
		return x.NumSlots
	}
	return 0
}

func (x *StateHistoryMeta) GetSchemaVer() uint32 {
	if x != nil {
		return x.SchemaVer
	}
	return 0
}

// AccountDelta captures the pre-block state of one account at one block, as
// a serialized blob. We capture the entire marshalled corepb.Account rather
// than mirroring its fields one-by-one for three reasons:
//
//  1. The Account proto evolves (shielded fields, freeze-V2 additions,
//     resource model refinements). A structured AccountDelta would force a
//     synchronized schema bump every time the upstream Account changes; a
//     blob survives field additions transparently.
//  2. Reconstruction is trivial: unmarshal account_proto_pre → done. No
//     field-by-field "apply rollback" merge logic to maintain.
//  3. The storage overhead (~150-400 B per touched account vs ~80 B for a
//     structured proto) is noise next to the ~2.4 TB mainnet archive total
//     called out in the spec.
//
// Code and contract metadata live OUTSIDE the Account proto in rawdb (under
// the c- and ct- prefixes respectively); they are mutable per account and
// can change independently of the Account row (SetCode, CREATE2 resurrect,
// SELFDESTRUCT-then-recreate-with-different-code). They are captured as
// separate pre-image blobs so the delta is self-sufficient for read paths.
//
// Slot storage (TVM contract storage cells) is NOT in this proto: those are
// captured by the sh-s- prefix with the raw 32-byte pre-value as the value
// — no per-row protobuf overhead, no per-slot wrapper.
type AccountDelta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 21-byte TRON address. Redundant with the key (the rawdb key also embeds
	// the address) but kept inline so a row is self-describing for
	// pruning/diagnostics.
	Addr []byte `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// existed_pre = false means the account did NOT exist before this block —
	// i.e. this block created it. Read paths use this sentinel to distinguish
	// a created-this-block account from one that merely had a zero-balance
	// pre-state. account_proto_pre/code_pre/contract_meta_pre are expected to
	// be empty when existed_pre = false.
	ExistedPre bool `protobuf:"varint,2,opt,name=existed_pre,json=existedPre,proto3" json:"existed_pre,omitempty"`
	// Marshalled corepb.Account at block N-1 (before this block's mutations).
	// Empty when existed_pre = false. Captures EVERY in-proto field —
	// balance, votes, asset/assetV2 maps, frozen/frozenV2/unfrozenV2 lists,
	// tron_power, old_tron_power, AccountResource sub-message, owner/
	// witness/active permissions, the resource sliding-window fields, etc.
	AccountProtoPre []byte `protobuf:"bytes,3,opt,name=account_proto_pre,json=accountProtoPre,proto3" json:"account_proto_pre,omitempty"`
	// Contract code at block N-1, if any (stored under the c- prefix in
	// rawdb, not inside the Account proto). Empty when the account had no
	// code pre-block. CREATE2-collide-then-recreate and SELFDESTRUCT-then-
	// recreate paths can change this independently of account_proto_pre.
	CodePre []byte `protobuf:"bytes,4,opt,name=code_pre,json=codePre,proto3" json:"code_pre,omitempty"`
	// Marshalled contractpb.SmartContract at block N-1, if any (stored under
	// the ct- prefix in rawdb, not inside the Account proto). Empty when the
	// account had no contract metadata pre-block. Carries ABI + creator-
	// address fields that VM_actuator mutates.
	ContractMetaPre []byte `protobuf:"bytes,5,opt,name=contract_meta_pre,json=contractMetaPre,proto3" json:"contract_meta_pre,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccountDelta) Reset() {
	*x = AccountDelta{}
	mi := &file_core_historystate_historystate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDelta) ProtoMessage() {}

func (x *AccountDelta) ProtoReflect() protoreflect.Message {
	mi := &file_core_historystate_historystate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDelta.ProtoReflect.Descriptor instead.
func (*AccountDelta) Descriptor() ([]byte, []int) {
	return file_core_historystate_historystate_proto_rawDescGZIP(), []int{1}
}

func (x *AccountDelta) GetAddr() []byte {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *AccountDelta) GetExistedPre() bool {
	if x != nil {
		return x.ExistedPre
	}
	return false
}

func (x *AccountDelta) GetAccountProtoPre() []byte {
	if x != nil {
		return x.AccountProtoPre
	}
	return nil
}

func (x *AccountDelta) GetCodePre() []byte {
	if x != nil {
		return x.CodePre
	}
	return nil
}

func (x *AccountDelta) GetContractMetaPre() []byte {
	if x != nil {
		return x.ContractMetaPre
	}
	return nil
}

// HistoryConfig is the sentinel record at sh-cfg- describing the local
// history index's mode and retention window. Written once by operator
// startup logic; consulted by Slice 5's background pruner.
type HistoryConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical mode: 0 = full (prune beyond prune_window), 1 = archive (keep
	// history forever). Wider enum room reserved for future modes.
	Mode uint32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// For full mode only: blocks older than (solidified - prune_window) are
	// eligible for deletion. Ignored in archive mode.
	PruneWindow uint64 `protobuf:"varint,2,opt,name=prune_window,json=pruneWindow,proto3" json:"prune_window,omitempty"`
	// Oldest block number with history available locally. 0 if the index is
	// empty. Maintained by the writer and the pruner.
	FirstBlock uint64 `protobuf:"varint,3,opt,name=first_block,json=firstBlock,proto3" json:"first_block,omitempty"`
	// Newest block number with history available locally. 0 if the index is
	// empty. Bumped on every successful block commit.
	LastBlock uint64 `protobuf:"varint,4,opt,name=last_block,json=lastBlock,proto3" json:"last_block,omitempty"`
	// Schema version, in lockstep with StateHistoryMeta.schema_ver. A
	// mismatch at startup must refuse to launch with a clear "rebuild your
	// archive" error — see the spec's backwards-compat section.
	SchemaVer     uint32 `protobuf:"varint,5,opt,name=schema_ver,json=schemaVer,proto3" json:"schema_ver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryConfig) Reset() {
	*x = HistoryConfig{}
	mi := &file_core_historystate_historystate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryConfig) ProtoMessage() {}

func (x *HistoryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_core_historystate_historystate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryConfig.ProtoReflect.Descriptor instead.
func (*HistoryConfig) Descriptor() ([]byte, []int) {
	return file_core_historystate_historystate_proto_rawDescGZIP(), []int{2}
}

func (x *HistoryConfig) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *HistoryConfig) GetPruneWindow() uint64 {
	if x != nil {
		return x.PruneWindow
	}
	return 0
}

func (x *HistoryConfig) GetFirstBlock() uint64 {
	if x != nil {
		return x.FirstBlock
	}
	return 0
}

func (x *HistoryConfig) GetLastBlock() uint64 {
	if x != nil {
		return x.LastBlock
	}
	return 0
}

func (x *HistoryConfig) GetSchemaVer() uint32 {
	if x != nil {
		return x.SchemaVer
	}
	return 0
}

var File_core_historystate_historystate_proto protoreflect.FileDescriptor

const file_core_historystate_historystate_proto_rawDesc = "" +
	"\n" +
	"$core/historystate/historystate.proto\x12\rgtron.history\"\xa7\x01\n" +
	"\x10StateHistoryMeta\x12\x1b\n" +
	"\tblock_num\x18\x01 \x01(\x04R\bblockNum\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\x12\x1b\n" +
	"\tnum_addrs\x18\x03 \x01(\rR\bnumAddrs\x12\x1b\n" +
	"\tnum_slots\x18\x04 \x01(\rR\bnumSlots\x12\x1d\n" +
	"\n" +
	"schema_ver\x18\x05 \x01(\rR\tschemaVer\"\xbc\x01\n" +
	"\fAccountDelta\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\fR\x04addr\x12\x1f\n" +
	"\vexisted_pre\x18\x02 \x01(\bR\n" +
	"existedPre\x12*\n" +
	"\x11account_proto_pre\x18\x03 \x01(\fR\x0faccountProtoPre\x12\x19\n" +
	"\bcode_pre\x18\x04 \x01(\fR\acodePre\x12*\n" +
	"\x11contract_meta_pre\x18\x05 \x01(\fR\x0fcontractMetaPreJ\x04\b\x06\x10\x14\"\xa5\x01\n" +
	"\rHistoryConfig\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\rR\x04mode\x12!\n" +
	"\fprune_window\x18\x02 \x01(\x04R\vpruneWindow\x12\x1f\n" +
	"\vfirst_block\x18\x03 \x01(\x04R\n" +
	"firstBlock\x12\x1d\n" +
	"\n" +
	"last_block\x18\x04 \x01(\x04R\tlastBlock\x12\x1d\n" +
	"\n" +
	"schema_ver\x18\x05 \x01(\rR\tschemaVerB9Z7github.com/tronprotocol/go-tron/proto/core/historystateb\x06proto3"

var (
	file_core_historystate_historystate_proto_rawDescOnce sync.Once
	file_core_historystate_historystate_proto_rawDescData []byte
)

func file_core_historystate_historystate_proto_rawDescGZIP() []byte {
	file_core_historystate_historystate_proto_rawDescOnce.Do(func() {
		file_core_historystate_historystate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_historystate_historystate_proto_rawDesc), len(file_core_historystate_historystate_proto_rawDesc)))
	})
	return file_core_historystate_historystate_proto_rawDescData
}

var file_core_historystate_historystate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_core_historystate_historystate_proto_goTypes = []any{
	(*StateHistoryMeta)(nil), // 0: gtron.history.StateHistoryMeta
	(*AccountDelta)(nil),     // 1: gtron.history.AccountDelta
	(*HistoryConfig)(nil),    // 2: gtron.history.HistoryConfig
}
var file_core_historystate_historystate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_historystate_historystate_proto_init() }
func file_core_historystate_historystate_proto_init() {
	if File_core_historystate_historystate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_historystate_historystate_proto_rawDesc), len(file_core_historystate_historystate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_historystate_historystate_proto_goTypes,
		DependencyIndexes: file_core_historystate_historystate_proto_depIdxs,
		MessageInfos:      file_core_historystate_historystate_proto_msgTypes,
	}.Build()
	File_core_historystate_historystate_proto = out.File
	file_core_historystate_historystate_proto_goTypes = nil
	file_core_historystate_historystate_proto_depIdxs = nil
}
